First sprint
ClevertecFrontendLab/sprint1-jglobe pull request #1
Opened 2023-01-31 18:18 UTC by jglobe

PR for first sprint.

2023-01-31 20:03 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/jglobe/1675195435/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/jglobe/1675195435/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/jglobe/1675195435/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/jglobe/1675195435/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/jglobe/1675195435/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/jglobe/1675195435/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/jglobe/1675195435/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/jglobe/1675195435/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/jglobe/1675195435/content-window.png)

2023-01-31 20:09 UTC, klichkovskiy requested changes

2023-01-31 20:09 UTC, klichkovskiy commented on src/pages/book/book-page.jsx
> +          <h5 className={styles.title}>
Это просто текст. Не нужно заголовки делать h5

2023-01-31 20:09 UTC, klichkovskiy commented on src/pages/book/book-page.jsx
> +          <div className={styles.reviews}>
промапать
![image](https://user-images.githubusercontent.com/62481116/215870791-97cdf207-f023-44a9-9b96-cc606fb2f11a.png)
сделать как в макете

2023-01-31 20:09 UTC, klichkovskiy commented on src/components/molecules/menu/menu.jsx
> +    <nav className={styles.menu}>
промапать

2023-02-01 07:53 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/jglobe/1675237986/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/jglobe/1675237986/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/jglobe/1675237986/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/jglobe/1675237986/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/jglobe/1675237986/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/jglobe/1675237986/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/jglobe/1675237986/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/jglobe/1675237986/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/jglobe/1675237986/content-window.png)

2023-02-01 07:54 UTC, klichkovskiy approved these changes

2023-02-01 07:56 UTC, merged